feat: add dependencies for preview
italia/guida-sviluppo-gestione-software-libero pull request #25
Opened 2021-04-05 21:49 UTC by astagi

This PR adds dependencies to run a preview of this guide locally

2021-04-12 10:33 UTC, astagi commented
@libremente Docker image is ready!

2021-04-14 08:45 UTC, libremente requested changes

2021-04-14 08:45 UTC, libremente commented on requirements.txt
> +Sphinx==3.4.3
Can we please move also this file to the `configuration` folder? That would be "safer" in the Docs Italia context, thanks!

2021-04-14 08:57 UTC, libremente approved these changes

2021-04-14 08:57 UTC, merged