feat: add 2nd chapter
italia/guida-sviluppo-gestione-software-libero pull request #26
Opened 2021-04-12 12:30 UTC by astagi

2021-04-14 09:43 UTC, bfabio requested changes

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +selezionando sulla barra in altoΩ a destra, il bottone “Sign In”.
```suggestion
selezionando sulla barra in alto a destra, il bottone “Sign In”.
```

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +-  i contributi non riguardano personalizzazioni e customizzazioni del
```suggestion
-  i contributi non riguardano personalizzazioni del
```

2021-04-14 09:43 UTC, bfabio commented on .github/workflows/broken-links-service.yml
> +          exclude_urls: https://gitlab.com/comune-reuso,https://www.ncsc.gov.uk/co
```suggestion
          exclude_urls: https://gitlab.com/comune-reuso
```

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +repository all’interno di una organizzazione
```suggestion
repository all’interno di una organizzazione::
```

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +\| \|-- README
```suggestion
  ComuneDiReuso
|-- software-protocollo
|     |-- LICENSE
|     `-- README
|
|-- software-pec
|     |-- LICENSE
|     `-- README
```

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +un’organizzazione, è possibile seguire i seguenti passi:
```suggestion
un’organizzazione è possibile seguire i seguenti passi:
```

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +| Al termine, dopo una serie di passaggi di verifica, premendo sul tasto
```suggestion
Al termine, dopo una serie di passaggi di verifica, premendo sul tasto
```

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +Per creare un’organizzazione, è possibile seguire i seguenti passi:
```suggestion
Per creare un’organizzazione è possibile seguire i seguenti passi:
```

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +https://bitbucket.org/comune-reuso/.
```suggestion
|image8|

L’URL del team così creato sarà https://bitbucket.org/comune-reuso/.
```

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +**organization.**
```suggestion
3. Selezionare il bottone **Turn comune-reuso into an organization.**
```

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +   :height: 2.71875in
```suggestion
```

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +   "Librerie di test Java").
I remember this was removed, but maybe I missed later discussions.

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +-  Non nominare il progetto come il marchio di qualcun altro.
```suggestion
-  Non chiamare il progetto come il marchio di qualcun altro.
```

2021-04-14 09:43 UTC, bfabio commented on amministratori-pubblici/gestire-un-software-nel-suo-ciclo-di-vita-1.rst
> +-  | Cambiare la descrizione sul repository e all’interno del file
```suggestion
-  Cambia la descrizione sul repository e all’interno del file
```

2021-04-14 09:46 UTC, bfabio commented
@astagi I'd use `version: "3.5"` in `docker-compose.yml` for us old Debian users :sweat_smile:

2021-04-14 10:26 UTC, astagi commented on amministratori-pubblici/contribuire-al-software-open-source-sviluppato-da-altri-1.rst
> +Capitolo a sé stante: aspetti di security
Uhm I don't know, @libremente thoughts?

2021-04-14 10:30 UTC, astagi commented on .github/workflows/broken-links-service.yml
> +          exclude_urls: https://gitlab.com/comune-reuso,https://www.ncsc.gov.uk/co
@bfabio unfortunately the url checker breaks the rst url during checking, in order to avoid to make it fail https://www.ncsc.gov.uk/c has been added to exclude_urls list

2021-04-14 10:36 UTC, astagi commented
> @astagi I'd use `version: "3.5"` in `docker-compose.yml` for us old Debian users 😅

Done!

2021-04-14 10:41 UTC, libremente commented on amministratori-pubblici/contribuire-al-software-open-source-sviluppato-da-altri-1.rst
> +Capitolo a sé stante: aspetti di security
Correct, let's remove it for now

2021-04-14 10:42 UTC, libremente commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +   "Librerie di test Java").
Let's remove it then

2021-04-14 10:44 UTC, libremente commented
> @astagi I'd use `version: "3.5"` in `docker-compose.yml` for us old Debian users sweat_smile

See #27 @bfabio

2021-04-14 10:46 UTC, bfabio commented on .github/workflows/broken-links-service.yml
> +          exclude_urls: https://gitlab.com/comune-reuso,https://www.ncsc.gov.uk/co
@astagi the correct URL is https://www.ncsc.gov.uk/collection/cloud-security, but it was truncated by the conversion putting it in a table I think.

It's in the security section so I didn't fix it because maybe we won't publish it for now (waiting for feedback in the other comment)

2021-04-14 11:50 UTC, astagi commented on amministratori-pubblici/rilasciare-un-nuovo-software-open-source.rst
> +   "Librerie di test Java").
Done @libremente @bfabio

2021-04-14 11:51 UTC, astagi commented on amministratori-pubblici/contribuire-al-software-open-source-sviluppato-da-altri-1.rst
> +Capitolo a sé stante: aspetti di security
Done @libremente @bfabio

2021-04-14 19:13 UTC, bfabio commented on .github/workflows/broken-links-service.yml
> +          exclude_urls: https://gitlab.com/comune-reuso,https://www.ncsc.gov.uk/co
@astagi we can remove this now with the security section gone

2021-04-14 19:13 UTC, bfabio approved these changes

2021-04-14 19:36 UTC, libremente commented on amministratori-pubblici.rst
> +======================================
```suggestion
===============================
```

2021-04-14 19:36 UTC, libremente commented on amministratori-pubblici.rst
> +  amministratori-pubblici/gestire-un-software-nel-suo-ciclo-di-vita-1.rst
Why the trailing `1`?

2021-04-15 07:02 UTC, libremente requested changes

2021-04-15 07:02 UTC, libremente commented on amministratori-pubblici/gestire-un-software-nel-suo-ciclo-di-vita.rst
> +.. _gestire-un-software-nel-suo-ciclo-di-vita-1:
@astagi watch out that modifying the filename implies also changing its references throughout the text like this one ^^

2021-04-15 07:21 UTC, astagi commented on amministratori-pubblici/gestire-un-software-nel-suo-ciclo-di-vita.rst
> +.. _gestire-un-software-nel-suo-ciclo-di-vita-1:
sorry @libremente missed that! fixed

2021-04-15 07:28 UTC, libremente approved these changes
LGTM let's try to merge :rocket:

2021-04-15 07:29 UTC, libremente commented
@astagi I will squash and merge, ok for you?

2021-04-15 07:35 UTC, merged

2024-09-13 14:18 UTC, Fresh2316 approved these changes