feat: aggiunta glossario da LG 68/69
italia/guida-sviluppo-gestione-software-libero pull request #40
Opened 2022-04-11 14:02 UTC by ruphy

#39

2022-04-11 16:11 UTC, valerio-bozzolan commented on glossario.rst
> +Repertorio o Repository
Inviterei a non adottare "repertorio" perchè sarebbe una traduzione un po' creativa. Alcuni usano "deposito" ma anche qui è un po' creativo, sebbene già più usuale.

2022-04-11 16:12 UTC, valerio-bozzolan commented on glossario.rst
> +    riproduzione o ridistribuzione, imposti dal titolare dei diritti di
correggerei in «imposti da chi detiene i diritti d'autore» perchè non si parla di diritto economico ma di copyright.

2022-04-11 16:14 UTC, valerio-bozzolan commented on glossario.rst
> +    Sottoprodotto realizzato durante lo sviluppo del *software* che aiuta
Non sono riuscito a trovare "artefatti" nel documento

https://docs.italia.it/italia/developers-italia/guida-sviluppo-gestione-software-libero/it/stabile/search.html?check_keywords=yes&area=default&q=Artefatti

Forse si può eliminare questa voce.

2022-04-11 16:17 UTC, valerio-bozzolan commented on glossario.rst
> +    sistemi di ticketing, processi per la contribuzione di codice da
Nella spiegazione si può evitare "sistemi di ticketing" (che meriterebbe un'altra voce nel glossario) scrivendo invece "sistemi per tenere traccia dei problemi o delle proposte"

2022-04-11 16:18 UTC, valerio-bozzolan commented on glossario.rst
> +    dal CAD (art. 69) con il quale una amministrazione distribuisce
"CAD" → "Codice Amministrazione Digitale "

2022-04-11 16:23 UTC, valerio-bozzolan commented on glossario.rst
> +    è un *software* distribuito in modalità *software* as a Service.
"Wikipedia" non è un esempio corretto di SaaS perchè non è un software fornito come servizio ma è un servizio e basta (che puoi replicare a tua volta ma rimane un servizio).

Cambierei da "che non viene installato sulle postazioni degli operatori, ma che avviene attraverso l'accesso remoto a un server, per esempio collegandosi con un browser ad un indirizzo." a "che non viene installato dal cliente finale (sui computer o sui server del cliente) ma che è erogato dai server del fornitore." o qualcosa del genere.

2022-04-11 16:37 UTC, valerio-bozzolan commented on glossario.rst
> +
Aggiungerei un piccolo paragrafo introduttivo, ad esempio:

Segue un elenco di alcuni termini e del loro rispettivo significato al fine di migliorare la comprensione del documento.

2022-04-11 16:53 UTC, valerio-bozzolan commented on glossario.rst
> +    altrimenti sarebbero riservati da diritti di privativa.
Testo proposto:

> Il testo legale che permette al titolare dei diritti d'autore di un'opera (*software*, contenuti, dati, ...) di concedere determinati diritti anche agli utilizzatori finali.
> 
> In assenza di una licenza esplicita, si assume generalmente «tutti i diritti riservati», quindi gli utilizzatori finali non possono usare, studiare, modificare, diffondere l'opera.

----

A questo punto introdurrei anche questa definizione:

> Licenza libera
>
> Una Licenza che concede tutti i seguenti diritti e senza restringere le loro applicazioni: diritto di utilizzo, studio, modifica e condivisione. Un elenco delle licenze libere è disponibile a questo indirizzo: https://www.gnu.org/licenses/license-list.html (tutte quelle segnate come "free license") insieme a tutte quelle elencate a questo indirizzo: https://opensource.org/licenses/alphabetical

O qualcosa del genere

2022-04-11 17:47 UTC, ruphy commented on glossario.rst
> +Repertorio o Repository
aggiungerei deposito allora, ma lascerei anche repertorio che ogni tanto si usa

2022-04-11 17:49 UTC, ruphy commented on glossario.rst
> +Open Source
mi piace come suggerimento!
nel testo aggiungerei anche una chiarificazione tipo:

> come leggiamo su Wikipedia, l'Enciclopedia libera, “i termini [software libero](https://it.wikipedia.org/wiki/Software_libero) e [open source](https://it.wikipedia.org/wiki/Open_source) vengono usati per indicare quella che è sostanzialmente la stessa cosa”. Generalmente gli utilizzatori del termine software libero preferiscono porre un accento sull’aspetto etico del software, mentre chi preferisce “open source” ha un focus sull’aspetto pratico. A noi interessano entrambi gli aspetti, dunque useremo entrambi i termini in modo interscambiabile. Del resto tutti i software open source sono anche liberi e viceversa.

2022-04-11 17:51 UTC, ruphy commented on glossario.rst
> +    Sottoprodotto realizzato durante lo sviluppo del *software* che aiuta
concordo, questo arriva dalle LG

2022-04-11 17:51 UTC, ruphy commented on glossario.rst
> +    Sottoprodotto realizzato durante lo sviluppo del *software* che aiuta
great catch!

2022-04-11 17:51 UTC, ruphy commented on glossario.rst
> +    riproduzione o ridistribuzione, imposti dal titolare dei diritti di
+1, hai voglia di proporre un testo alternativo?

2022-04-18 11:14 UTC, ruphy commented on introduzione.rst
> +i software open source sono anche software libero e viceversa.
@bfabio @libremente

2022-04-28 09:20 UTC, bfabio commented on glossario.rst
> +    aperto è un formato riconosciuto da un ente di standardizzazione e
```suggestion
    aperto è riconosciuto da un ente di standardizzazione e
```

2022-04-28 09:20 UTC, bfabio commented on glossario.rst
> +    Modalità di rappresentazione del dato.
Questo lo toglierei e lascerei spiegare tutto a "Formato di dato aperto"

2022-04-28 09:20 UTC, bfabio commented on glossario.rst
> +    di cooperare e di scambiare informazioni in maniera automatica,
```suggestion
    di cooperare e di scambiare informazioni in maniera automatica e strutturata,
```

2022-04-28 09:20 UTC, bfabio commented on glossario.rst
> +    Una licenza aperta è una licenza che concede al pubblico, i diritti di
```suggestion
    Nel caso del software, una licenza aperta è una licenza che concede a chiunqui usi un software, i diritti di
```

2022-04-28 09:20 UTC, bfabio commented on glossario.rst
> +    software; per fare ciò, è necessario anche che il codice sorgente
```suggestion
    uso, copia, modifica, distribuzione di copie anche modificate; per fare ciò, è necessario anche che il codice sorgente
```

2022-04-28 09:20 UTC, bfabio commented on glossario.rst
> +    nel caso di soluzioni SaaS) sono prerequisiti per evitare fenomeni
```suggestion
    nel caso di soluzioni :term:`SaaS`) sono prerequisiti per evitare fenomeni
```

2022-04-28 09:20 UTC, bfabio commented on glossario.rst
> +    Vedi: Software libero.
IMO la voce di Wikipedia è da correggere e le due cose non sono sinonimi

2022-04-28 09:20 UTC, bfabio commented on glossario.rst
> +    esempio nel CAD Art 69, comma 1).
```suggestion
    esempio nel :term:`CAD` Art 69, comma 1).
```

2022-04-28 09:20 UTC, bfabio commented on glossario.rst
> +    dal CAD (art. 69) con il quale una amministrazione distribuisce
```suggestion
    dal :term:`CAD`  (art. 69) con il quale una amministrazione distribuisce
```

2022-04-28 09:20 UTC, bfabio commented on glossario.rst
> +    Total Cost of Ownership: Approccio utilizzato per valutare tutti i
```suggestion
    Total Cost of Ownership: approccio utilizzato per valutare tutti i
```

2022-04-28 09:20 UTC, bfabio commented on introduzione.rst
> +i software open source sono anche software libero e viceversa.
Non dovremmo riportare questo perché IMO è sbagliato. Ci sono licenze approvate da OSI che non sono software libero

2022-05-02 13:04 UTC, libremente commented on glossario.rst
> +
Concordo

2022-05-02 13:04 UTC, libremente commented on glossario.rst
> +Ecosistema aperto di sviluppo
Ping @bfabio su questo punto

2022-05-04 14:18 UTC, ruphy commented on introduzione.rst
> +i software open source sono anche software libero e viceversa.
```suggestion
useremo entrambi i termini in modo interscambiabile. Infatti, praticamente
tutti i software open source sono anche software libero e viceversa.
```

2022-05-04 14:19 UTC, ruphy commented on glossario.rst
> +    Modalità di rappresentazione del dato.
```suggestion
```

2022-05-05 07:42 UTC, libremente commented on glossario.rst
> +Ecosistema aperto di sviluppo
Converti in una issue dedicata? @bfabio Così procediamo al merge di questa, grazie

2022-05-05 09:04 UTC, bfabio commented on glossario.rst
> +Ecosistema aperto di sviluppo
@libremente fatto

2022-05-05 14:31 UTC, libremente requested changes
My 2 cents please review @ruphy @bfabio

2022-05-06 16:49 UTC, bfabio commented on glossario.rst
> +    (es. C o Visual Basic) dal quale si deriva il programma finale che
Il writing-toolkit [suggerisce di usare "es."](https://docs.italia.it/italia/designers-italia/writing-toolkit/it/bozza/suggerimenti-di-scrittura/punteggiatura-e-grammatica.html#esempio-o-es)

2022-05-06 16:58 UTC, bfabio commented on introduzione.rst
> +tutti i software open source sono anche software libero e viceversa.
Sono d'accordo :+1:

2022-05-06 16:58 UTC, bfabio commented on introduzione.rst
> +tutti i software open source sono anche software libero e viceversa.
```suggestion
```

2022-05-27 09:37 UTC, bfabio commented on glossario.rst
> +Licenza aperta o Licenza Open Source
Apro una issue dedicata

2022-05-27 10:08 UTC, libremente approved these changes
Mergiamo questa così abbiamo la baseline e poi continuiamo a aggiornare @bfabio

2022-05-27 10:22 UTC, merged